site_name: My CTF Challenges

theme:
  name: material
  icon:
    logo: fontawesome/regular/flag
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: indigo

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: amber
      accent: amber

nav:
  - Accueil: index.md
  - 24@CTF 2024:
    - OSINT:
      - SteganOsint 1: 24hCTF-2024/OSINT/SteganOsint-1/README.md
      - SteganOsint 2: 24hCTF-2024/OSINT/SteganOsint-2/README.md
      - Sur les traces de Scofield 1: 24hCTF-2024/OSINT/Sur-les-traces-de-Scofield-1/README.md
      - Sur les traces de Scofield 2: 24hCTF-2024/OSINT/Sur-les-traces-de-Scofield-2/README.md
      - Sur les traces de Scofield 3: 24hCTF-2024/OSINT/Sur-les-traces-de-Scofield-3/README.md
  - UnitedCTF 2024:
    - Programming:
      - Fortune L33t3r 1: UnitedCTF-2024/Programming/Fortune-l33t3r-1/README.md
      - Fortune L33t3r 2: UnitedCTF-2024/Programming/Fortune-l33t3r-2/README.md
  - Mois de la cyber 2024:
    - OSINT:
      - Katherin Stallings a disparu 1: Mois-de-la-cyber-2024/OSINT/Katherin-Stallings-a-disparu-1/README.md
      - Katherin Stallings a disparu 2: Mois-de-la-cyber-2024/OSINT/Katherin-Stallings-a-disparu-2/README.md
      - Katherin Stallings a disparu 3: Mois-de-la-cyber-2024/OSINT/Katherin-Stallings-a-disparu-3/README.md
  - h0h0h0day CTF 2024:
    - Steganography:
      - Dialing To Merry Festivities: h0h0h0day-CTF-2024/Steganography/Dialing-to-merry-festivities/README.md
  - PolyPwn 2025:
    - Network:
      - TitaNIC: PolyPwn-2025/Network/TitaNIC/README.md
